### PR TITLE
v2: ndslice API rework, extern(C++) support

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by timotheecour** [comment]
@9il I was always confused about the `packs` argument; after this PR, `packs` argument seems to have completely disappeared in favor of the simpler `size_t N`; was `packs` a mis-feature that has 0 advantage compared to `N` or are there cases where it's needed?
Thanks!

**Comment by jmh530** [comment]
@9il Would it make sense to do a ColumnMajorIterator, or is this something that can only be easily accomplished by changing how functions like popFront work in Slice?

**Comment by 9il** [comment]
@jmh530 Interesting, i did not think about. Could you please write a proposal draft how popFront/front/empty/opIndex functions should behave with ColumnMajorIterator?

**Comment by jmh530** [comment]
@9il Work is sucking up quite a bit of my time lately, so I wish I could be more detailed. The idea was influenced by Eigen's _Options described in [1] and [2]. At a minimum, I had assumed that if they allowed a compile-time switch for it, then it could be implemented by incorporating it into the definition of Slice. In implementing this in ndslice, functions like popFront would just need a static if that depends on the equivalent of __Options. There are a lot of nice things about the design. So I suppose I was wondering if something like a ColumnMajorIterator could work without making the adjustments to those functions. The idea would be that bumping the iterator would just behave differently than a normal iterator. However, this may have cache locality issues. I don't know. After sleeping on it, I'm not sure I can do it with good performance, but if I find time I'll try to sketch something out.

[1] https://eigen.tuxfamily.org/dox/classEigen_1_1Matrix.html
[2] https://eigen.tuxfamily.org/dox/group__TopicStorageOrders.html

**Comment by 9il** [comment]
Looks like any additional API will make ndslice package overcomplicated.

In other hand, `Array(T, size_t N, Layout layout)` container can be added. It can be quite simple and may have value semantic like C++ `vector`. Also, a method like `view` can return a slice, that can be used without memory copy.

**Pull request merged**
