### PR TITLE
Add ndslice.chunks module

### PR DESCRIPTION
**Pull request by 9il**
@andralex @wilzbach  @ljubobratovicrelja @thewilsonator @dataPulverizer 

Mir Algorithm basic API is stable enough and we can start to do reviews! Please help with that)

This PR contains fast multidimensional random access `chunks`. It has multidimensional slicing, builtin dimension transposition, allows to get underlying slice during life time.

Motivation of this addition is cache oriented algorithms. For example, see Chapter 1 at  [The Science of Programming Matrix Computations](http://www.cs.utexas.edu/users/rvdg/tmp/TSoPMC.pdf)

### CODE REVIEW

**Comment by dataPulverizer** [comment]
Thank you very much for the update. Been very busy lately but will hopefully get some time at the end of the week to take a detailed look.

Well done

**Comment by jmh530** [comment]
You might add an example to mir.chunks showing that (if?) you can apply sum to the chunks. I would imagine that would be a key use case. This should allow you to row sum or column sum, if I'm not mistaken.

**Comment by 9il** [comment]
@jmh530 could you describe what do you mean using a small example?

**Comment by jmh530** [comment]
@9il I was thinking something like below would work, but I may have gotten something wrong. I haven't played with the code yet.

unittest
{
    import mir.ndslice.slice : sliced;
    import mir.ndslice.chunks: chunks, isChunks;
    import mir.ndslice.topology: iota;
    import mir.math.sum: sum;

    // 0 1 2 3 4 5 6 7 8 9 10
    auto sl = iota(11);
    // 0 1 2 | 3 4 5 | 6 7 8 | 9 10
    auto ch = sl.chunks(3);
    // 3 | 12 | 21 | 19
    auto s = ch.sum();
    assert(s == [3, 12, 21, 19].sliced);
}

**Comment by 9il** [comment]
@jmh530 , added - 0780e47c79a7513c4f295343b85f4b7f38ff14e4

**Pull request merged**
