### PR TITLE
Update package.d doc for median filter example

### PR DESCRIPTION
**Pull request by aferust**
I only changed the code comments to update the median filter example for docs. did not touch anything else.

### CODE REVIEW

**Comment by jmh530** [comment]
Why not use the median function from mir.math.stat?
http://mir-algorithm.libmir.org/mir_math_stat.html#.median

If I recall correctly, that text was from before mir.math.stat existed.

**Comment by aferust** [comment]
> Why not use the median function from mir.math.stat? http://mir-algorithm.libmir.org/mir_math_stat.html#.median If I recall correctly, that text was from before mir.math.stat existed.
> […](#)
> On Fri, Mar 29, 2024 at 4:18 AM aferust ***@***.***> wrote: I only changed the code comments to update the median filter example for docs. did not touch anything else. ________________________________ You can view, comment on, or merge this pull request online at: #468 Commit Summary [7c90d9a](https://github.com/libmir/mir-algorithm/commit/7c90d9aa3be048acd81fb5a515e31fc02875d31d) Update package.d doc for median filter example File Changes (1 file) M source/mir/ndslice/package.d (32) Patch Links: https://github.com/libmir/mir-algorithm/pull/468.patch https://github.com/libmir/mir-algorithm/pull/468.diff — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

I believe the docs there are for explaining the usage of the ndslice not to show how to perform a median filter.

**Comment by 9il** [comment]
Thank you for the update! Unfortunately, my Circle CI account is under sanctions, and it doesn't update online docs anymore.

**Comment by aferust** [comment]
sorry to hear that. It is always weird that politics affects our lives in this way.  There must be some third-party solutions for it.

**Comment by 9il** [comment]
> There must be some third-party solutions for it.

Sure, it just needs some time. Mir's solution uses Circle CI + Docker + AWS. Circle CI is OK, but I don't have time to work on Mir anymore. It requires creating a new Circle CI account, setting up AWS keys in GitHub, and digging into the AWS setup, which I completely forgot.

I will accept changes if you or other Mir members want to transfer documentation generation to another AWS bucket and website.

**Comment by 9il** [comment]
Wow, thank you for the great news! Then it is just really very outdated:
- meson build scripts (list of files)
- compiler versions in the docker images
- documentation bugs
Still a lot of work, but at least twice less than I thought.

**Pull request merged**
