### PR TITLE
Add skewness

### PR DESCRIPTION
**Pull request by jmh530**
Compared to `VarianceAlgo`, `SkewnessAlgo` has one additional algorithm. I complement `SkewnessAlgo.twoPass` with `SkewnessAlgo.threePass`. 

`SkewnessAlgo.threePass` is the most accurate version because it calculates the `mean` and `variance` first in two passes and then scales each value in the input by them. 

`SkewnessAlgo.twoPass` is similar to above, but calculates the `mean` and `variance` in one pass and then scales the input by them. I include a UT where it provides the same answer as `SkewnessAlgo.online` and `SkewnessAlgo.threePass` and then another where it and `SkewnessAlgo.online` provide the incorrect answer. As with `VarianceAlgo.twoPass`, there are cases where it can be faster to go through a slice twice rather than do the `online` calculation. Nevertheless, I do not have as strong an opinion about whether to include, but it is not much additional effort in the implementation.

### CODE REVIEW

**Comment by 9il** [comment]
@jmh530 Please accept my apologies for the delay with a review for this PR and #290. I will need more time.

**Comment by jmh530** [comment]
No problem at all. I’m working on kurtosis as well.

**Comment by 9il** [comment]
The problem with current PRs and kurtosis is that this stuff is more about ontology rather than algorithms.
Plus, this stuff looks too specialized.

In other hand, ontology is an important thing as well.

BTW, we can create a `mir-stat` repository for `mir.stat` package. What do you think?

**Comment by jmh530** [comment]
I am ok with that, but I feel like some thought should be given with its
interaction with mir.random. Ideally the package would eventually have cdf,
pdf, etc in there. Most languages have some kind of consistent API between
those and random number generation.

**Comment by 9il** [comment]
https://github.com/libmir/mir-stat

CDF/PDF and random variables implementations are independent one of each other.
The API can be consistent in terms of naming, and optionally parameters. The scripting languages API approach when the random number generation is provided with PDF/CDF looks weird for native languages because we should care more about dependencies and compilation speed.

**Comment by 9il** [comment]
I will add docs for mir-stat when it got some code.

**Comment by jmh530** [comment]
How much of the current mir.math.stat should be in mir-stat instead?

On pdf/cdf, there are two main approaches that people take. One is with
functions as in R, e.g. pnorm/qnorm. Julia  and Python take a more
object-oriented approach where you create a normal variable and then call
pdf/cdf functions from that. mir-random shares a little more in common with
the second approach, though you use the normal variable like a callable,
rather than calling a random member function. Moreover, I would be a little
worried about conflicts if there is a NormalVariable or normalVar in
mir-stat as well.

**Comment by 9il** [comment]
> How much of the current mir.math.stat should be in mir-stat instead?

I think only ` dispersion`.

> One is with functions as in R, e.g. pnorm/qnorm. Julia and Python take a more object-oriented approach where you create a normal variable and then call pdf/cdf functions from that.

For basic distribution, the R way looks more comfortable `normalPDF` and `normalCDF`. At least it will allow us to compile code faster. For very complex distributions we can have parameter packs like `NormalInverseGaussianParam` and `NormalInverseGaussianParamGamma` for other parametrization of the same distribution.

**Comment by jmh530** [comment]
Sounds good. `center` is another one that might be more appropriate there.

**Comment by 9il** [comment]
> center

Is very common in financial code, would be nice to have it in the main repo

**Comment by jmh530** [comment]
Implemented in `mir-stat` in [#6](https://github.com/libmir/mir-stat/pull/6).

**Pull request closed without merging**
