### PR TITLE
Don't use __vector if SIMD unsupported (was making some DMD builds fail)

### PR DESCRIPTION
**Pull request by n8sh**

### CODE REVIEW

**Comment by 9il** [comment]
All prs are fail on travis

**Comment by n8sh** [comment]
@9il 
>All prs are fail on travis

I am aware of this: I am trying to fix the build problems in 'master' one-by-one. [It looks like](https://github.com/libmir/mir-algorithm/commits/master) the master branch has been failing builds in travis-ci for the last 3 days.

Aside from this issue and https://github.com/libmir/mir-algorithm/pull/107, there is something weird happening with unittests in `mir.ndslice.algorithm.d` and `mir.ndslice.iterator.d`.

**Comment by n8sh** [comment]
The specific error that this patch removes can be seen in https://travis-ci.org/libmir/mir-algorithm/jobs/294051867:
```
source/mir/interpolate/package.d(543,9): Error: SIMD vector types not supported on this platform
source/mir/interpolate/linear.d(365,26): Error: template instance mir.interpolate.vectorize!(AliasCall!(LinearKernel!double, "opCall", 0u), double, 2u, 1u) error instantiating
```

**Comment by 9il** [comment]
Ok, I will take a look

**Comment by 9il** [comment]
Forgot, This is DMD bug that is specific for test code

**Comment by n8sh** [comment]
@9il 
>Forgot, This is DMD bug that is specific for test code

Do you know what the bug is?

**Comment by 9il** [comment]
https://issues.dlang.org/show_bug.cgi?id=17943

**Pull request merged**
