### PR TITLE
Add String.opEquals(AA)

### PR DESCRIPTION
**Pull request by nordlow**

### CODE REVIEW

**Comment by nordlow** [comment]
Ready now.

**Comment by 9il** [comment]
Needs rebase

**Comment by nordlow** [comment]
Rebased and improved StringMap.opEquals further. Ready now.

**Comment by nordlow** [comment]
Rebased and improved StringMap.opEquals further. Ready now.

**Comment by nordlow** [comment]
Rebased and improved StringMap.opEquals further. Ready now.

**Comment by nordlow** [comment]
Rebased and improved StringMap.opEquals further. Ready now.

**Pull request merged**
