### PR TITLE
Update CI files to include requested changes

### PR DESCRIPTION
**Pull request by hatf0**
See https://github.com/libmir/mir-ion/issues/16 for more detail.

### CODE REVIEW

**Comment by 9il** [comment]
Please get rid of appveyor

**Comment by 9il** [comment]
Some CI jobs fails becaues of runners goes to out of memory, especially windows.
Possible solution is:
 - Either split `ndslice`, `bignum` and the rest of `ndslice` tests.
 - Or use [-lowmem](https://dlang.org/dmd-osx.html#switch-lowmem) flag. I am not sure if it works for DMD.

**Comment by hatf0** [comment]
> Please get rid of appveyor

I'm personally not able to get rid of AppVeyor -- it's under your account, so you'll have to do that

**Comment by jmh530** [comment]
Would there be any benefit to moving unit tests that are not documentation tests to a separate folder by themselves?

**Comment by 9il** [comment]
> Would there be any benefit to moving unit tests that are not documentation tests to a separate folder by themselves?

I don't think so. It is usefull to have then right in the file.

**Pull request merged**
