### PR TITLE
add mir.ndslice.fuse and a a huge work on qualifier propagation 

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by thewilsonator** [comment]
Any reason `inout` won't do the job here?
Also the PR should probably be split into addition of `@optmath` , join and  qualifiers.

**Comment by 9il** [comment]
Yeah, but it is was just a join + bugfixes for it. Please let me to push it as single one (small time constraints).

`@optmath` was added before for all mir. This is just missing one.

`inout` is useless for composed types. For example for Dlang ranges:
```d
const r = zip(a, b.map!fabs", iota(a.length));
// Phobos Ranges: r and r[] are useless
// Mir ndslice: r[] is full featured and safe range with deep constant elements.
```

**Comment by thewilsonator** [comment]
Fair enough.

**Comment by 9il** [comment]
Hm, Thanks for note about `@optmath`. It was added for interpolation, but only constant interpolation may have it. Also it make Travis fails for release unittests.

**Comment by jmh530** [comment]
You might add something in the documentation about how mir.ndslice.join is different from concatenation. Personally, I see them as very similar and at the very least could be part of the same module (bikeshed: would prefer that the name join is reserved for any sql-like behavior, as in R's dplyr).

**Comment by 9il** [comment]
@jmh530 What name you would suggest?

**Comment by jmh530** [comment]
@9il Naming is tricky, but I would probably use fuse, combine is another alternative.

In join's favor, it has similar behavior as std.array's join and if join is added in the future, then someone can use a fully qualified name to avoid issues. Also, even in SQL there are lots of types of joins, left join, right join, anti join, etc. You usually don't just use join...you would use full join.

**Comment by 9il** [comment]
> fuse

LGTM

**Pull request merged**
